### ISSUE TITLE
Input fields do not display in Firefox

### ISSUE THREAD

**Issue by betsystevens** [HarshKapadia2/calculator#1]
Hello Harsh!   
Thank you for the great video and documentation on git!

I was running your calculator demo from my Firefox browser and the row of input fields did not display as they do in a Chrome browser. Only the first two input fields and part of the third are visible, making the calculator unusable. I've attached an image.
The calculator rendered fine for me in a Chrome browser.

If you make this change on line 125 in the index.css file, the input fields will display in both browsers.

```
input
{
    flex: 0.2;
    width: 20%;
...
```
```
input
{
    flex: 0.2;
    max-width: 20%;
...
```

I am looking to make my first pull-request to a repo on git-hub, I am new to open source contributing. I could make the aforementioned change as a 
*fork -> clone -> edit -> pull request* workflow  
Please let me know.

Thank you.
<img width="561" alt="calculator" src="https://user-images.githubusercontent.com/8739700/95006285-8d784680-05c8-11eb-9e25-4150f1d1ed3e.png">

**Comment by betsystevens** [comment]
I have seen this workaround on [github](https://github.com/philipwalton/flexbugs/issues/152) and on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1242914)

Instead of my solution of:
```
  max-width:  20%;
```
Use:
```
  min-width:  0;
```
to solve this issue.

**Comment by HarshKapadia2** [comment]
> Thank you for the great video and documentation on git!

Hey Betsy, thank you so much for going through both. It means a lot to me!

> I am looking to make my first pull-request to a repo on git-hub, I am new to open source contributing. I could make the aforementioned change as a
fork -> clone -> edit -> pull request workflow
Please let me know.

Go ahead! I'll assign you to this issue.

Are you participating in [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)? If yes, let me know so that I can include this repo in the event for your contribution to count.

Also, thank you so much for trying out the calculator and raising an issue!

**Comment by betsystevens** [comment]
> > Thank you for the great video and documentation on git!
> 
> Hey Betsy, thank you so much for going through both. It means a lot to me!
> 
> > I am looking to make my first pull-request to a repo on git-hub, I am new to open source contributing. I could make the aforementioned change as a
> > fork -> clone -> edit -> pull request workflow
> > Please let me know.
> 
> Go ahead! I'll assign you to this issue.
> 
> Are you participating in [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)? If yes, let me know so that I can include this repo in the event for your contribution to count.
> 
> Also, thank you so much for trying out the calculator and raising an issue!

**Comment by betsystevens** [comment]
I will do this!   

I haven't thought much about Hactoberfest 2020, I don't see a downside so sure, you can add it. I will sign up.

I accidentally closed this issue so I reopened it.  I would most welcome any suggestions or corrections about any of my activity during this process. Thank you again for making it so pleasant so far!

**Comment by betsystevens** [comment]
I've signed up for Hacktoberfest, I'm all in! Again, thanks for the guidance!

**Comment by HarshKapadia2** [comment]
Thank you so much for PR #2 which resolves the issue. I wasn't even aware of this issue with Flexbox in Firefox! Thank you!

All the best for Hacktoberfest 2020!
